### ISSUE TITLE
Error mounting the component due to a missing check on Hub

### ISSUE THREAD

**Issue by popeio** [getsentry/sentry-rrweb#11]
Hello there,

It looks like there is a missing check at [this line of the index.ts file](https://github.com/getsentry/sentry-rrweb/blob/master/src/index.ts#L52), where you wrongly assume that a call to `getCurrentHub().getIntegration(...)` will surely return an initialized instance.

There are situations, for example during the startup of a Nuxt.js bundle, during which the Hub is actually `null`. 
This is just someone who let the error slip: [just ten lines below](https://github.com/getsentry/sentry-rrweb/blob/master/src/index.ts#L62) there is an analogous check to ensure that a Hub has been returned, prior to operating on it.

To be more specific on this specific case, this issue arised when attempting to mount Sentry on a Vue/Nuxt project. I'll leave a stack trace here just for the sake of completeness.

BTW this does not appear to be an issue of RRWeb, but rather an issue of your wrapper around it.

Should you need more information, I'm here to (try to) help :)
Thanks!

```
TypeError: Cannot read property 'events' of null
    at emit (index.es.js:29)
    at wrappedEmit (index.js:45)
    at takeFullSnapshot (index.js:63)
    at init_1 (index.js:102)
    at record (index.js:178)
    at SentryRRWeb.push../node_modules/@sentry/rrweb/dist/index.es.js.SentryRRWeb.setupOnce (index.es.js:19)
    at setupIntegration (integration.js:49)
    at integration.js:63
    at Array.forEach (<anonymous>)
    at setupIntegrations (integration.js:61)
    at BrowserClient.push../node_modules/@sentry/core/esm/baseclient.js.BaseClient.setupIntegrations (baseclient.js:147)
    at Hub.push../node_modules/@sentry/hub/esm/hub.js.Hub.bindClient (hub.js:57)
    at initAndBind (sdk.js:16)
    at Module.init (sdk.js:84)
    at sentry.js:15
    at _callee2$ (index.js:207)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (app.._.nuxt_A.js:2356)
    at _next (app.._.nuxt_A.js:2358)
```

**Comment by dcramer** [comment]
Thanks! Should be a simple fix. Will try to get something up before Monday.

**Comment by popeio** [comment]
No problem @dcramer, thanks for the quick response!
If you don't have time for this, we can fork this, fix it and merge it back. As you prefer :)

**Comment by dcramer** [comment]
I mentioned this in the PR, but I think the fix is broader than just handling this error. It's likely we need to retry recording events until the integration is available, which has its own set of problems. Realistically I think the answer here is we need to either force a new snapshot upon registration, and/or we need a hook in Sentry to instantiate rrweb _post_ Hub registration. That will create complexity in any environment with multiple contexts, but I'm not sure we can solve for that.

**Comment by popeio** [comment]
You might want to take a look at what the guys at Nuxt.js have done with [their Sentry integration](https://github.com/nuxt-community/sentry-module/blob/master/lib/plugin.lazy.js).

In any case, I fear that postponing snapshotting via RRWeb is not an option, the reason being: you cannot record what you are not yet there to witness :)

If you take a look at what the fellows at Nuxt.js did, they basically keep buffering events until they have got everything ready to operate. Once they complete the startup, they simply flush the queue, throw it all at Sentry and live on.

I do not think you could do the same in this case: how can you start handling requests to "record the screen" (simplifying a bit here, but keep in mind that we are talking about a Sentry plugin, which is supposedly initialized after Sentry itself (I might have gotten this wrong, if this is the case feel free to correct me!)). I mean, how can a Sentry plugin request Sentry to do something before its own startup has completed?

I believe the point of this bug here is just due to the fact that when Sentry starts up it takes a moment to build everything up and be totally ready to operate, while RRWeb immediately tries to kick in and do its work. Which is good, but as you ended up saying: allowing this behaviour might require quite a bit of additional work, in order to introduce something like a `onSentryReady` hook in the core Sentry package.

That's why I was suggesting to simply add the quick `if` as a quick fix for the moment: it allows the component to function correctly, without taking away critical functionality. 

All this to say: I've read [your PR](https://github.com/getsentry/sentry-rrweb/pull/13) and you are totally right, this corrects the bug, not the error, which is more of a logical error than a typo-like one.

Thanks for your help BTW!

**Comment by dcramer** [comment]
Need to test it yet, but #14 seems like a cleaner approach to me.

**Comment by popeio** [comment]
Just taking a quick look, but basically, by moving `events` into the local context, you should be able to avoid talking directly to the Sentry instance, and you can fire RRWeb up much sooner, not having to worry about Sentry itself. 

If I got it right, it seems perfectly reasonable to me, and it should not require that much of a rework aside for what you have already done, at least based on that little I know about Sentry's internals!

**Comment by dcramer** [comment]
Can you try out 0.2.0 and let me know if you're still seeing issues?

**Comment by popeio** [comment]
@dcramer sure, I'll try and give it a go tomorrow, should we still face any issue I'll make sure to report them

Thanks!
