### ISSUE TITLE
Replay view in sentry.io is empty

### ISSUE THREAD

**Issue by havard024** [getsentry/sentry-rrweb#12]
Hi,

I've added the sentry rrweb integration to an angular application, but my "REPLAY" section sentry.io is showing empty, see below screenshot.

<img width="1388" alt="Screen Shot 2020-10-09 at 8 05 43 PM" src="https://user-images.githubusercontent.com/2212037/95617308-825f6380-0a6b-11eb-89a1-0c0807c3aa00.png">

I'm using the following versions:

```
"@sentry/browser": "^5.25.0",
"@sentry/tracing": "^5.25.0",
"@sentry/rrweb": "^0.1.2",
"rrweb": "^0.9.7",
```

The application is an angular 9 application (using the ionic framework)

I'm initializing sentry in app.module.ts 

```
Sentry.init({
    dsn: '___DSN___,
    integrations: [
        new Sentry.Integrations.TryCatch({
            XMLHttpRequest: false,
        }),
        new SentryRRWeb({

        })
    ],
    release: VERSION,
    environment: environment.env
});
```

And to test I'm manually capturing an exception by clicking a button which triggers the below code

`Sentry.captureException('Manually triggered Sentry exception');`

**Comment by havard024** [comment]
Might it be related to this warning from the dev console?

<img width="786" alt="Screen Shot 2020-10-09 at 11 25 12 PM" src="https://user-images.githubusercontent.com/2212037/95633720-936a9d80-0a88-11eb-8dbf-874a0fc513f5.png">

I tried to drill down into the issue, and it looks like this line
`var self = getCurrentHub().getIntegration(SentryRRWeb)`

does not return anything, which causes the error on the below line since self is not defined.

`self.events.push(event);`

**Comment by havard024** [comment]
Sorry, I didn't check the existing issues, #11 is talking about the same warning I see in the dev console

**Comment by dcramer** [comment]
@havard024 are you also using nuxt?

**Comment by dcramer** [comment]
Actually I believe #11 is about the integration side - it looks like we've captured a replay in your case but it isn't displaying. Mind shooting me an email with a link to the issue? david at sentry.io.

**Comment by havard024** [comment]
> @havard024 are you also using nuxt?

I'm not using nuxt, I'm using ionicframework



> Actually I believe #11 is about the integration side - it looks like we've captured a replay in your case but it isn't displaying. Mind shooting me an email with a link to the issue? david at sentry.io.

Thanks! I've dropped you an email with a link to the issue

**Comment by dcramer** [comment]
Can you try out 0.2.0 and let me know if you're still seeing issues?

**Comment by havard024** [comment]
Thanks! Upgrading to 0.2.0 made the replay appear in sentry 👌
