### ISSUE TITLE
rrweb error from SentryRRWeb

### ISSUE THREAD

**Issue by csicky** [getsentry/sentry-rrweb#16]
After adding the SentryRRWeb addon to Sentry I get this error in Sentry
`TypeError MutationObserver.processMutations(rrweb/es/rrweb/src/record/mutation)`

It is a bit funny that there is an error from a Sentry plugin and then Sentry catches it :)

**Comment by dcramer** [comment]
Can you confirm the version of the packages you're using? Both for rrweb and sentry-rrweb?

**Comment by dcramer** [comment]
Likely overlaps with #15

**Comment by csicky** [comment]
```
    "@sentry/browser": "5.26.0",
    "@sentry/integrations": "5.26.0",
    "@sentry/rrweb": "0.1.2",
```

**Comment by csicky** [comment]
I keep seeing the error `Cannot read property 'value' of null` coming from sentry/rrweb. We use Sentry to see errors and react on them, not to generate tens of thousands. I have added ignore rule on this error, but still I am not sure what to do, remove rrweb integration, or wait for it to become stable?
It is nice to see a replay when investigating an error.

![image](https://user-images.githubusercontent.com/3931907/112516115-9e4b8d00-8d9f-11eb-886e-bf848ae6dc40.png)
![image](https://user-images.githubusercontent.com/3931907/112516187-b15e5d00-8d9f-11eb-848e-08fef34443a6.png)

**Comment by dcramer** [comment]
@csicky can you open an issue on rrweb and make sure you note the version of rrweb you're using. If you haven't already, you also might want to consider upgrading (or checking changes in newer versions) to see if its already been resolved.

**Comment by csicky** [comment]
using   
``` 
    "@sentry/browser": "6.2.3",
    "@sentry/integrations": "6.2.3",
    "@sentry/rrweb": "0.2.0",
    "rrweb": "0.9.14",
```

**Comment by csicky** [comment]
I don't have time to investigate errors in a plugin of a product I use to investigate my errors. I just wanted to signal here these errors are happening and while the idea is nice, to be able to see what the user did before the error happened, it is not worth the trouble and overhead of a product used to report errors generate errors itself.

**Comment by dcramer** [comment]
@csicky rrweb is not created by Sentry. the plugin you're using is specificaly to enable the support of another open source library. I'm going to close this ticket as there is nothing for us to act upon here..

**Comment by csicky** [comment]
I have followed instructions from Sentry, I didn't know about rrweb from other place, didn't know it existed before. In my opinion, since Sentry is a paid product, it shouldn't advertise integration with something which is not stable and then decline any responsibility. But that is jut how I see it. I will remove rrweb and keep using Sentry, which is useful as it is.

**Comment by firashamila33** [comment]
smae here , I am using only the following, its throwing hundreds of errors : 
```
    "@sentry/angular": "^6.3.5",
    "@sentry/rrweb": "^0.3.1",
    "@sentry/tracing": "^6.3.5",
    "@sentry/cli": "^1.64.1",
```
