### ISSUE TITLE
sentry 20.8.0 integrate @sentry/rrweb error

### ISSUE THREAD

**Issue by llisonly** [getsentry/sentry-rrweb#17]
"@sentry/rrweb": "^0.2.0",
"@sentry/browser": "^5.27.1",
"rrweb": "^0.9.9",

![image](https://user-images.githubusercontent.com/4126495/97656040-6a469700-1aa1-11eb-94ae-27d5359d99a4.png)
![image](https://user-images.githubusercontent.com/4126495/97656072-85190b80-1aa1-11eb-896c-1ae612735d17.png)
![image](https://user-images.githubusercontent.com/4126495/97656089-919d6400-1aa1-11eb-81fc-5ef0f7289d47.png)
![image](https://user-images.githubusercontent.com/4126495/97656174-c90c1080-1aa1-11eb-987f-00113fe2179d.png)
but the sentry web event detail do not show replay button

**Comment by dcramer** [comment]
THere's any number of reasons this could be working incorrectly on self-hosted. You'd want to debug the workers and file storage layers to make sure they're actually persisting, and you can check the File/EventAttachment tables to identify if the record is present.

Closing this as there's nothing actionable to be done here.
