### ISSUE TITLE
Latest change to @sentry/rrweb should be published as 0.3

### ISSUE THREAD

**Issue by boh-dan** [getsentry/sentry-rrweb#23]
Latest change to @sentry/rrweb was published with the previous version (0.2) to npm.  Please publish with the new version in order to make it available.

**Comment by dcramer** [comment]
Looking into this - if that's true it would appear our automations failed somewhere.

**Comment by mitsuhiko** [comment]
I changed the description of the issue. From my understanding the actual problem is that the commit to master was not released yet.

**Comment by dcramer** [comment]
We published 0.3, however there is an issue that needs resolved with the changes to uploading to npm (see #27)
