### ISSUE TITLE
Dist file missing in 0.3.0 Release

### ISSUE THREAD

**Issue by junsushin-dev** [getsentry/sentry-rrweb#27]
### Environment

How do you use Sentry?
self-hosted/on-premise v21.3.1

Which SDK and version?
@sentry/rrweb v0.3.0

### Steps to Reproduce

1. download @sentry/rrweb package from npm/yarn registry
2. find that it's empty... LOL

### Expected Result

Dist file should be present in published package

### Actual Result

<img width="1180" alt="스크린샷 2021-04-16 오후 2 39 45" src="https://user-images.githubusercontent.com/32405358/114976859-a2ac2700-9ec1-11eb-9949-0820fbf2fa41.png">

**Comment by dcramer** [comment]
Sorry about that. We've been migrating a bunch of project to a more maintainable way to upload artifacts to services like npm and it looks like we didn't throughly test this one.

We'll make sure we get this resolved tomorrow US time.

**Comment by junsushin-dev** [comment]
@dcramer Thanks for the fast follow-up! :)
