### ISSUE TITLE
Integration is not working. No Replay section on sentry dashboard

### ISSUE THREAD

**Issue by andrei10k** [getsentry/sentry-rrweb#36]
// package.json
"@sentry/browser": "^6.3.4",
"@sentry/rrweb": "^0.3.1",
"rrweb": "^0.9.14"

// index.js
import { SENTRY_CONFIG } from './config'
import * as Sentry from '@sentry/browser'

if (process.env.NODE_ENV === 'production') {
  Sentry.init(SENTRY_CONFIG)
}

// config.js
import SentryRRWeb from '@sentry/rrweb'

export const SENTRY_CONFIG = {
  dsn: '********',
  integrations: [new SentryRRWeb()]
}

I'm using react and webpack 5. Doesn't appear to do anything. There is no Replay section on sentry dashboard. Am I doing something wrong?

**Comment by dcramer** [comment]
There's two things you can check:

1) Are you seeing a network request that is transmitting to an attachments endpoint?
2) Are you seeing any form of rrweb.json in the attachments list in the issue details?

**Comment by andrei10k** [comment]
@dcramer neither of the 2. i don't have anything in the attachments tab. 
Strange thing, just now I noticed this error on sentry: 

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/14038494/118523789-29188a80-b746-11eb-817d-437a82eda46b.png">

**Comment by dcramer** [comment]
@andrei10k mind posting that on the [rrweb issue tracker](https://github.com/rrweb-io/rrweb)? Looks like a bug for sure and possible its what causing it to fail to capture transactions.

**Comment by andrei10k** [comment]
done. https://github.com/rrweb-io/rrweb/issues/559

**Comment by bruno-garcia** [comment]
Please note this repository has been superseded and will no longer be updated.

Check https://github.com/getsentry/sentry-javascript/tree/master/packages/replay#sentry-session-replay instead, we're happy respond to issues, review and merge PRs there.
