### ISSUE TITLE
Add documentation on the effects on memory usage and performance on the client side

### ISSUE THREAD

**Issue by PMLP-novo** [getsentry/sentry-rrweb#41]
Thanks for this awesome plugin. To me it is very unclear what the effects on my users are my using this. It would be really nice if you could add some thoughts and also some ideas for how to mitigate eventual problems related to very long running sessions or whatever that might be problematic.

**Comment by dcramer** [comment]
Fair ask - even for rrweb as a core. I think your concern is going to be bandiwdth over anything else though. CPU/Memory are often non-issues for device-based software given its a single session. The concern here is its holding on to a lot of events it has to transmit. Each event doesn't take up much memory (we have gigabytes after all), but even if it were to take up a megabyte of data payload that can be a lot for slow connections.
