### ISSUE TITLE
Sentry rrweb does not work with tunnelling

### ISSUE THREAD

**Issue by PMLP-novo** [getsentry/sentry-rrweb#48]
### Environment
I use a self hosted sentry inside a corperate VPC, so all ip adresses are inside this VPC
Since we are using https we have setup sentry tunnelling in accordance with https://docs.sentry.io/platforms/javascript/guides/react/troubleshooting/#using-the-tunnel-option

```
Sentry.init({
    environment: window.location.hostname,
    dsn: "http://3989c4dfe9d54aa785c121560ee9d176@10.78.7.108:9000/3", // our self hosted site 
    integrations: [
      new Integrations.BrowserTracing(),
      new SentryRRWeb({
        maskAllInputs: false,
      }),
    ],
    tunnel: Config.apiEndpoint + "sentry/tunnel",
    // Tunnel sentry errors via the backend to avoid CORS problems
    // https://docs.sentry.io/platforms/javascript/troubleshooting/#using-the-tunnel-option
  });
}
```

Which SDK and version?

    "@sentry/browser": "^4.5.3",
    "@sentry/react": "^6.10.0",
    "@sentry/rrweb": "^0.3.1",
    "@sentry/tracing": "^6.10.0",

### Steps to Reproduce
There was a bug and the rrweb request was send to the dsn not the tunnel

### Expected Result
The result was send to the tunnel that would pas it to sentry

### Actual Result
The result failed to send and we did not get our nice video

![image](https://user-images.githubusercontent.com/54025656/139040216-55c57c80-9444-49ad-a14e-8b08587a68c4.png)

**Comment by sevtdy** [comment]
also, the iframe tag doesn't have `allow-scripts` attribute, SPA app can't load properly.

**Comment by sneko** [comment]
Hi,

On my side the rrweb binary is passed through the DSN URL whereas the rest of Sentry report is passed through the tunnel.

Is it the normal behavior for "third-party" integrations?

<img width="506" alt="image" src="https://user-images.githubusercontent.com/8195958/164245121-0d6b78af-9d3a-4cfa-867f-951322e3bada.png">


<img width="470" alt="image" src="https://user-images.githubusercontent.com/8195958/164245163-780eaa86-3f54-4499-90ce-a91e6c5ff14e.png">

**Comment by bruno-garcia** [comment]
I believe this is resolved in the new Replay SDK since it uses the `envelope` endpoint. Please note this repository has been superseded and will no longer be updated.

Please check https://github.com/getsentry/sentry-javascript/tree/master/packages/replay#sentry-session-replay instead, we're happy respond to issues, review and merge PRs there.
