### ISSUE TITLE
Needs a minimum event threshold.

### ISSUE THREAD

**Issue by davidflypei** [getsentry/sentry-rrweb#61]
Needs a minimum event threshold. Right now as long as there is at least one event in the recording it will send. That one event could be the first "initialize" event which does nothing. It can't be played in Sentry as the replayer needs at least two events. Would be nice to be able to set a threshold to reduce clutter on the server.

**Comment by bruno-garcia** [comment]
I believe this is resolved in the new Replay SDK. Please note this repository has been superseded and will no longer be updated.

Please check https://github.com/getsentry/sentry-javascript/tree/master/packages/replay#sentry-session-replay instead, we're happy respond to issues, review and merge PRs there.
