### ISSUE TITLE
Cannot find module 'rrweb/src/types' or its corresponding type declarations.

### ISSUE THREAD

**Issue by dovvan** [getsentry/sentry-rrweb#66]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
"rrweb": "^2.0.0-alpha.1", 
"@sentry/angular": "^7.10.0",
"@sentry/integrations": "^7.10.0",
"@sentry/rrweb": "^0.3.3",
"@sentry/tracing": "^7.10.0",

Also tried 7.11 on sentry

### Steps to Reproduce

1. Install sentry rrweb with npm install --save @sentry/rrweb rrweb
2. Register the integration in Sentry.init
import SentryRRWeb from "@sentry/rrweb";
integrations: [
    new SentryRRWeb(),
3. Try to build the project.

### Actual Result

Error: node_modules/rrdom/es/diff.d.ts:2:85 - error TS2307: Cannot find module 'rrweb/src/types' or its corresponding type declarations.

2 import type { canvasMutationData, canvasEventWithTime, inputData, scrollData } from 'rrweb/src/types';
                                                                                      ~~~~~~~~~~~~~~~~~


Error: node_modules/rrdom/es/index.d.ts:3:85 - error TS2307: Cannot find module 'rrweb/src/types' or its corresponding type declarations.

3 import type { canvasMutationData, canvasEventWithTime, inputData, scrollData } from 'rrweb/src/types';
                                                                                      ~~~~~~~~~~~~~~~~~

Error: node_modules/rrweb/typings/types.d.ts:395:19 - error TS2304: Cannot find name 'FontFaceDescriptors'.

395     descriptors?: FontFaceDescriptors;
                      ~~~~~~~~~~~~~~~~~~~


Error: node_modules/rrweb/typings/types.d.ts:520:26 - error TS2304: Cannot find name 'FontFace'.

520         FontFace: typeof FontFace;
                             ~~~~~~~~

**Comment by glompix** [comment]
this is because `rrweb@2.0.0-alpha*` moved typings around

try `yarn add rrweb@1.1.3`. worked for me!

**Comment by bruno-garcia** [comment]
This repository has been superseded and will no longer be updated.

Please check https://github.com/getsentry/sentry-javascript/tree/master/packages/replay#sentry-session-replay instead, we're happy respond to issues, review and merge PRs there.
